name: Heroku deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Add heroku remote origin
        run: |
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/app-laravel-samazon.git
      - name: Deploy app to Heroku
        run: |
          git subtree push --prefix samazon heroku main
